### ISSUE TITLE
cas filter not working anymore

### ISSUE THREAD

**Issue by FZachlod** [pwm-project/pwm#105]
we tried to apply the cas filters to the web.xml of the current snapshot which results into

SEVERE: Error filterStart
Nov 30, 2016 2:54:45 PM org.apache.catalina.core.StandardContext startInternal
SEVERE: Context [/pwm] startup failed due to previous errors

on startup.

cas filters work correctly with an older version from august.

**Comment by idwright** [comment]
Have you tried the code in the pull request associated to #78 ?

**Comment by FZachlod** [comment]
our latest (working) build was from August 1st. The pull request is from July so I assume this does not fix an error, which was induced after August 1st... furthermore we are still on CAS 3.5 so this has nothing to do with changes in CAS5.

but thank you anyway.

**Comment by idwright** [comment]
The pull request works against CAS 4.1 and was updated fairly recently.

You might have some mileage in just looking at the changes in web.xml - there are some changes there that are required for more recent versions of the cas client jar

**Comment by FZachlod** [comment]
after applying the suggested changes to web.xml  at least the war deploys successfully. But after logging in via CAS I get

2016-12-01T13:23:14Z, ERROR, tag.JspThrowableHandlerTag, jsp error reference 251FA1B8AC8E3CB326A08710C9209A3D08BE3C4D (stacktrace follows)
javax.servlet.ServletException: org.jasig.cas.client.validation.TicketValidationException: No principal was found in the response from the CAS server.
        at org.jasig.cas.client.validation.AbstractTicketValidationFilter.doFilter(AbstractTicketValidationFilter.java:227)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.jasig.cas.client.session.SingleSignOutFilter.doFilter(SingleSignOutFilter.java:97)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)
        at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1040)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:607)
        at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.jasig.cas.client.validation.TicketValidationException: No principal was found in the response from the CAS server.
        at org.jasig.cas.client.validation.Cas20ServiceTicketValidator.parseResponseFromServer(Cas20ServiceTicketValidator.java:98)
        at org.jasig.cas.client.validation.AbstractUrlBasedTicketValidator.validate(AbstractUrlBasedTicketValidator.java:201)
        at org.jasig.cas.client.validation.AbstractTicketValidationFilter.doFilter(AbstractTicketValidationFilter.java:204)
        ... 20 more

**Comment by FZachlod** [comment]
actually this change has to be made:

remove

        <init-param>
            <param-name>renew</param-name>
            <param-value>false</param-value>
        </init-param>

afterwards pwm will start again.

**Comment by FZachlod** [comment]
Created a pull request: https://github.com/pwm-project/pwm/pull/108
