### ISSUE TITLE
HTTPS not working, /config/token error message

### ISSUE THREAD

**Issue by thomasfriedl** [pwm-project/pwm#106]
I'm running PWM in a docker container.

I can't get https to work - I forced https in the web security section and uploaded our PFX certificate for our wildcard SSL certificate in the HTTPS Server section. 

I also set the application URL - it's a subdomain of our SSL wildcard certificate. 

When checking why HTTPS isn't working in chrome I can see that the app is still using the pwm self signed certificate and not the one I uploaded.

When looking in the logs I can see the following: 
`6. Dezember 2016 12:48:50 CET, ERROR, health.ApplianceStatusChecker, An error occurred checking appliance status: File '/config/token' does not exist (stacktrace follows)
java.io.FileNotFoundException: File '/config/token' does not exist
	at org.apache.commons.io.FileUtils.openInputStream(FileUtils.java:254)
	at org.apache.commons.io.FileUtils.readFileToString(FileUtils.java:1641)
	at org.apache.commons.io.FileUtils.readFileToString(FileUtils.java:1659)
	at password.pwm.health.ApplianceStatusChecker.getApplianceAccessToken(ApplianceStatusChecker.java:86)
	at password.pwm.health.ApplianceStatusChecker.doHealthCheck(ApplianceStatusChecker.java:48)
	at password.pwm.health.HealthMonitor.doHealthChecks(HealthMonitor.java:187)
	at password.pwm.health.HealthMonitor.access$400(HealthMonitor.java:48)
	at password.pwm.health.HealthMonitor$ScheduledUpdater.run(HealthMonitor.java:227)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)`

And also:
`6. Dezember 2016 12:46:21 CET, ERROR, health.ApplianceStatusChecker, Unable to read the hostname for the docker host, using default: 172.17.0.1 (stacktrace follows)
java.io.FileNotFoundException: File '/config/appliance-host' does not exist
	at org.apache.commons.io.FileUtils.openInputStream(FileUtils.java:254)
	at org.apache.commons.io.FileUtils.readFileToString(FileUtils.java:1641)
	at org.apache.commons.io.FileUtils.readFileToString(FileUtils.java:1659)
	at password.pwm.health.ApplianceStatusChecker.getApplianceHost(ApplianceStatusChecker.java:97)
	at password.pwm.health.ApplianceStatusChecker.doHealthCheck(ApplianceStatusChecker.java:47)
	at password.pwm.health.HealthMonitor.doHealthChecks(HealthMonitor.java:187)
	at password.pwm.health.HealthMonitor.access$400(HealthMonitor.java:48)
	at password.pwm.health.HealthMonitor$ImmediateUpdater.run(HealthMonitor.java:242)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)`

And:
`6. Dezember 2016 12:42:14 CET, ERROR, health.ApplianceStatusChecker, An error occurred checking appliance status: No route to host (Host unreachable) (stacktrace follows)
java.net.NoRouteToHostException: No route to host (Host unreachable)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:337)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:141)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55)
	at password.pwm.health.ApplianceStatusChecker.doHealthCheck(ApplianceStatusChecker.java:56)
	at password.pwm.health.HealthMonitor.doHealthChecks(HealthMonitor.java:187)
	at password.pwm.health.HealthMonitor.access$400(HealthMonitor.java:48)
	at password.pwm.health.HealthMonitor$ScheduledUpdater.run(HealthMonitor.java:227)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)`

Any ideas what I'm doing wrong? The same certificate works fine on other servers - I'm also using it for my Active Directory for LDAPS support.

**Comment by thomasfriedl** [comment]
Apparently my Chrome cached something - it's working now.
