### ISSUE TITLE
file lock problem

### ISSUE THREAD

**Issue by mbrbus** [pwm-project/pwm#117]
Hi,

I've built PWM and ran it under Tomcat 7.

There is a file lock problem.

Here is the stack trace

> 2017-01-11T11:33:15Z, DEBUG, pwm.PwmEnvironment, can't establish application file lock after 1m:50s, will retry;
2017-01-11T11:33:20Z, ERROR, pwm.PwmEnvironment, unable to obtain file lock on file /mnt/pwm/pwm_data/applicationPath.lock due to error: null
java.nio.channels.OverlappingFileLockException
        at sun.nio.ch.SharedFileLockTable.checkList(FileLockTable.java:255)
        at sun.nio.ch.SharedFileLockTable.add(FileLockTable.java:152)
        at sun.nio.ch.FileChannelImpl.tryLock(FileChannelImpl.java:1108)
        at java.nio.channels.FileChannel.tryLock(FileChannel.java:1155)
        at password.pwm.PwmEnvironment$FileLocker.attemptFileLock(PwmEnvironment.java:521)
        at password.pwm.PwmEnvironment.attemptFileLock(PwmEnvironment.java:462)
        at password.pwm.PwmEnvironment.waitForFileLock(PwmEnvironment.java:482)
        at password.pwm.PwmApplication.initialize(PwmApplication.java:211)
        at password.pwm.PwmApplication.<init>(PwmApplication.java:161)
        at password.pwm.http.ContextManager.initialize(ContextManager.java:202)
        at password.pwm.http.HttpEventManager.contextInitialized(HttpEventManager.java:100)
        at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:5099)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5615)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:147)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:899)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:875)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:652)
        at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:1092)
        at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1984)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
2017-01-11T11:33:20Z, DEBUG, pwm.PwmEnvironment, can't establish application file lock after 1m:55s, will retry;
2017-01-11T11:33:25Z, FATAL, pwm.PwmApplication, 5082 ERROR_STARTUP_ERROR (unable to obtain application path file lock)
2017-01-11T11:33:25Z, FATAL, http.ContextManager, unable to obtain application path file lock

**Comment by jrivard** [comment]
please ask for help on the pwm-general mailing list.
