### ISSUE TITLE
SSO problem : authenticated without a password, redirecting to login page

### ISSUE THREAD

**Issue by rrs91** [pwm-project/pwm#12]
Hi all

I've an issue using SSO Headers for authentication (PWm 1.7.1, OpenLDAP 2.3).
Once authenticated through, if i want to change my password or setup responses answers, i´m sent to the password page over and over again.

Extract from PWM.log

2015-11-18 11:49:39, TRACE, provider.JNDIProviderImpl, bind successful as uid=xzy,ou=users,dc=domain,dc=fr (47ms)
2015-11-18 11:49:39, TRACE, provider.ChaiProviderFactory, adding WatchdogWrapper to provider instance
2015-11-18 11:49:39, TRACE, provider.WatchdogWrapper, checking for user password expiration to adjust watchdog timeout
2015-11-18 11:49:39, TRACE, provider.ChaiProviderFactory, adding WireTraceWrapper to provider instance
2015-11-18 11:49:39, TRACE, provider.ChaiProviderFactory, adding StatisticsWrapper to provider instance
2015-11-18 11:49:39, TRACE, provider.WireTraceWrapper, begin id=18,op#1 method readStringAttribute(uid=xyz,ou=users,dc=domain,dc=fr,objectClass)
2015-11-18 11:49:39, TRACE, provider.WireTraceWrapper, finish id=18,op#1 result: "top" (1ms)
2015-11-18 11:49:39, INFO , operations.UserAuthenticator, {7m,[CN USER]} successful ssl authentication for uid=xyz,ou=users,dc=domain,dc=fr (56ms) [@IP Address user, @IP Address reverse proxy/]
2015-11-18 11:49:39, WARN , servlet.TopServlet, attempt to access functionality requiring password authentication, but password not yet supplied by actor, forwarding to password Login page
2015-11-18 11:49:39, DEBUG, servlet.TopServlet, {7m,[CN USER]} user is authenticated without a password, redirecting to login page [@IP Address user, @IP Address reverse proxy/]
2015-11-18 11:49:39, TRACE, pwm.SessionFilter, {7m,[CN USER]} GET request for: /pwm/private/Login (no params) [@IP Address user, @IP Address reverse proxy/]
2015-11-18 11:49:39, TRACE, util.MacroMachine, replaced Macro @User:ID@ with value: [CN USER]

Any help appreciated

Many thx

**Comment by rrs91** [comment]
Hi
I've tried with PWM 1.8.0 (11/18/2015).
I encounter thoses errors

2015-11-23T16:04:50Z, ERROR, filter.AuthenticationFilter, {z} 5015 ERROR_UNKNOWN (error during SSO_AUTH_HEADER authentication attempt: 5015 ERROR_UNKNOWN (no available unknown-pw authentication method)) [@IP, @IP]
2015-11-23T16:04:50Z, ERROR, http.PwmResponse, {z} 5015 ERROR_UNKNOWN (error during SSO_AUTH_HEADER authentication attempt: 5015 ERROR_UNKNOWN (no available unknown-pw authentication method)) [@IP, @IP]
2015-11-23T16:04:50Z, TRACE, filter.AuthenticationFilter, {z} user requested resource requiring authentication (/pwm/private/config/editor), but is not authenticated; redirecting to LoginServlet [@IP, @IP]
2015-11-23T16:04:50Z, WARN , filter.SessionFilter, {z} unhandled exception Cannot call sendRedirect() after the response has been committed [@IP, @IP] (stacktrace follows)
java.lang.IllegalStateException: Cannot call sendRedirect() after the response has been committed
        at org.apache.catalina.connector.ResponseFacade.sendRedirect(ResponseFacade.java:483)
        at javax.servlet.http.HttpServletResponseWrapper.sendRedirect(HttpServletResponseWrapper.java:138)
        at password.pwm.http.PwmHttpResponseWrapper.sendRedirect(PwmHttpResponseWrapper.java:62)
        at password.pwm.http.PwmRequest.sendRedirect(PwmRequest.java:185)
        at password.pwm.http.servlet.LoginServlet.redirectToLoginServlet(LoginServlet.java:268)
        at password.pwm.http.filter.AuthenticationFilter.processUnAuthenticatedSession(AuthenticationFilter.java:315)
        at password.pwm.http.filter.AuthenticationFilter.processFilter(AuthenticationFilter.java:110)
        at password.pwm.http.filter.AbstractPwmFilter.doFilter(AbstractPwmFilter.java:71)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
        at password.pwm.http.filter.AbstractPwmFilter$PwmFilterChain.doFilter(AbstractPwmFilter.java:110)
        at password.pwm.http.filter.CaptchaFilter.processFilter(CaptchaFilter.java:53)
        at password.pwm.http.filter.AbstractPwmFilter.doFilter(AbstractPwmFilter.java:71)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
        at password.pwm.http.filter.AbstractPwmFilter$PwmFilterChain.doFilter(AbstractPwmFilter.java:110)
        at password.pwm.http.filter.SessionFilter.processFilter(SessionFilter.java:82)
        at password.pwm.http.filter.AbstractPwmFilter.doFilter(AbstractPwmFilter.java:71)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
        at password.pwm.http.filter.AbstractPwmFilter$PwmFilterChain.doFilter(AbstractPwmFilter.java:110)
        at password.pwm.http.filter.ApplicationModeFilter.processFilter(ApplicationModeFilter.java:70)
        at password.pwm.http.filter.AbstractPwmFilter.doFilter(AbstractPwmFilter.java:71)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
        at password.pwm.http.filter.RequestInitializationFilter.doFilter(RequestInitializationFilter.java:95)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
        at password.pwm.http.filter.GZIPFilter.doFilter(GZIPFilter.java:67)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
        at password.pwm.http.filter.ApplicationStatusFilter.doFilter(ApplicationStatusFilter.java:35)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:99)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:407)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1004)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:589)
        at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.run(AprEndpoint.java:1822)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)

java.lang.IllegalStateException: Cannot call sendRedirect() after the response has been committed
        at org.apache.catalina.connector.ResponseFacade.sendRedirect(ResponseFacade.java:483)
        at javax.servlet.http.HttpServletResponseWrapper.sendRedirect(HttpServletResponseWrapper.java:138)
        at password.pwm.http.PwmHttpResponseWrapper.sendRedirect(PwmHttpResponseWrapper.java:62)
        at password.pwm.http.PwmRequest.sendRedirect(PwmRequest.java:185)
        at password.pwm.http.servlet.LoginServlet.redirectToLoginServlet(LoginServlet.java:268)
        at password.pwm.http.filter.AuthenticationFilter.processUnAuthenticatedSession(AuthenticationFilter.java:315)
        at password.pwm.http.filter.AuthenticationFilter.processFilter(AuthenticationFilter.java:110)
        at password.pwm.http.filter.AbstractPwmFilter.doFilter(AbstractPwmFilter.java:71)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
        at password.pwm.http.filter.AbstractPwmFilter$PwmFilterChain.doFilter(AbstractPwmFilter.java:110)
        at password.pwm.http.filter.CaptchaFilter.processFilter(CaptchaFilter.java:53)
        at password.pwm.http.filter.AbstractPwmFilter.doFilter(AbstractPwmFilter.java:71)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
        at password.pwm.http.filter.AbstractPwmFilter$PwmFilterChain.doFilter(AbstractPwmFilter.java:110)
        at password.pwm.http.filter.SessionFilter.processFilter(SessionFilter.java:82)
        at password.pwm.http.filter.AbstractPwmFilter.doFilter(AbstractPwmFilter.java:71)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
        at password.pwm.http.filter.AbstractPwmFilter$PwmFilterChain.doFilter(AbstractPwmFilter.java:110)
        at password.pwm.http.filter.ApplicationModeFilter.processFilter(ApplicationModeFilter.java:70)
        at password.pwm.http.filter.AbstractPwmFilter.doFilter(AbstractPwmFilter.java:71)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
        at password.pwm.http.filter.RequestInitializationFilter.doFilter(RequestInitializationFilter.java:95)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
        at password.pwm.http.filter.GZIPFilter.doFilter(GZIPFilter.java:67)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
        at password.pwm.http.filter.ApplicationStatusFilter.doFilter(ApplicationStatusFilter.java:35)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:99)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:407)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1004)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:589)
        at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.run(AprEndpoint.java:1822)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
2015-11-23T16:04:50Z, ERROR, filter.ApplicationStatusFilter, error while trying to detect application status: java.lang.IllegalStateException: Cannot call sendRedirect() after the response has been committed
2015-11-23T16:04:50Z, ERROR, filter.ApplicationStatusFilter, unable to satisfy incoming request, application is not available
2015-11-23T16:04:50Z, ERROR, tag.JspThrowableHandlerTag, jsp error reference 0508EDFBAED615A135BE4A49ADE17F1D9FFB02D5 (stacktrace follows)
java.lang.IllegalStateException: Cannot forward after response has been committed
        at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:349)
        at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:339)
        at password.pwm.http.filter.ApplicationStatusFilter.doFilter(ApplicationStatusFilter.java:53)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:99)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:407)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1004)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:589)
        at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.run(AprEndpoint.java:1822)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)

java.lang.IllegalStateException: Cannot forward after response has been committed
        at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:349)
        at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:339)
        at password.pwm.http.filter.ApplicationStatusFilter.doFilter(ApplicationStatusFilter.java:53)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:99)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:407)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1004)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:589)
        at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.run(AprEndpoint.java:1822)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)

**Comment by jrivard** [comment]
Please ask for help on the pwm-general google group.
