### ISSUE TITLE
configuration editor search

### ISSUE THREAD

**Issue by subst4nc3** [pwm-project/pwm#145]
hello,
after upgrade to the latest snapshot version, i can't do a search anymore... if i try to search for a parameter i got an "error 5015"
i have experienced also a problem on visualizing configuration summary on configuration manager page... same error....5015 

here the log output:08 marzo 2017 14:34:10 W. Europe Standard Time, FATAL, servlet.AbstractPwmServlet, 5015 ERROR_UNKNOWN (unexpected error processing request: null
java.lang.NullPointerException
	at password.pwm.config.value.VerificationMethodValue.toDebugString(VerificationMethodValue.java:166)
	at password.pwm.config.stored.StoredConfigurationImpl.toOutputMap(StoredConfigurationImpl.java:280)
	at password.pwm.http.servlet.configmanager.ConfigManagerServlet.showSummary(ConfigManagerServlet.java:364)
	at password.pwm.http.servlet.configmanager.ConfigManagerServlet.processAction(ConfigManagerServlet.java:147)
	at password.pwm.http.servlet.AbstractPwmServlet.handleRequest(AbstractPwmServlet.java:110)
	at password.pwm.http.servlet.AbstractPwmServlet.doGet(AbstractPwmServlet.java:61)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:624)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at password.pwm.http.filter.AbstractPwmFilter$PwmFilterChain.doFilter(AbstractPwmFilter.java:138)
	at password.pwm.http.filter.ConfigAccessFilter.processFilter(ConfigAccessFilter.java:87)
	at password.pwm.http.filter.AbstractPwmFilter.doFilter(AbstractPwmFilter.java:89)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at password.pwm.http.filter.AbstractPwmFilter$PwmFilterChain.doFilter(AbstractPwmFilter.java:138)
	at password.pwm.http.filter.AuthenticationFilter.processAuthenticatedSession(AuthenticationFilter.java:184)
	at password.pwm.http.filter.AuthenticationFilter.processFilter(AuthenticationFilter.java:119)
	at password.pwm.http.filter.AbstractPwmFilter.doFilter(AbstractPwmFilter.java:89)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at password.pwm.http.filter.AbstractPwmFilter$PwmFilterChain.doFilter(AbstractPwmFilter.java:138)
	at password.pwm.http.filter.SessionFilter.processFilter(SessionFilter.java:99)
	at password.pwm.http.filter.AbstractPwmFilter.doFilter(AbstractPwmFilter.java:89)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at password.pwm.http.filter.AbstractPwmFilter$PwmFilterChain.doFilter(AbstractPwmFilter.java:138)
	at password.pwm.http.filter.ApplicationModeFilter.processFilter(ApplicationModeFilter.java:73)
	at password.pwm.http.filter.AbstractPwmFilter.doFilter(AbstractPwmFilter.java:89)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at password.pwm.http.filter.RequestInitializationFilter.initializeServletRequest(RequestInitializationFilter.java:209)
	at password.pwm.http.filter.RequestInitializationFilter.doFilter(RequestInitializationFilter.java:128)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at password.pwm.http.filter.GZIPFilter.doFilter(GZIPFilter.java:73)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:956)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:436)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1078)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:318)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)

**Comment by subst4nc3** [comment]
hello,
seems that the issue is related to something with the old PwmConfiguration.xml...
after reconfiguring the application from scratch all problems are gone
