### ISSUE TITLE
Forgotten password email generates "Database Unavailable. If this error occurs repeatedly please contact your help desk."

### ISSUE THREAD

**Issue by jryberg** [pwm-project/pwm#148]
Running pwm-1.8.0-SNAPSHOT-2017-03-14T08_35_02Z-pwm-bundle

When I click forgot password and enter my username and press "SMS/Email verification" I got the following error message:

Database Unavailable. If this error occurs repeatedly please contact your help desk.

The log file are printing the following:

```
password.pwm.error.PwmUnrecoverableException: 5051 ERROR_DB_UNAVAILABLE (unexpected error trying to store token in datastore: 5051 ERROR_DB_UNAVAILABLE (put operation failed: String or binary data would be truncated.))
	at password.pwm.http.servlet.forgottenpw.ForgottenPasswordServlet.initializeAndSendToken(ForgottenPasswordServlet.java:1153)
	at password.pwm.http.servlet.forgottenpw.ForgottenPasswordServlet.forwardUserBasedOnRecoveryMethod(ForgottenPasswordServlet.java:1613)
	at password.pwm.http.servlet.forgottenpw.ForgottenPasswordServlet.processVerificationChoice(ForgottenPasswordServlet.java:329)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at password.pwm.http.servlet.ControlledPwmServlet.dispatchMethod(ControlledPwmServlet.java:101)
	at password.pwm.http.servlet.ControlledPwmServlet.processAction(ControlledPwmServlet.java:132)
	at password.pwm.http.servlet.AbstractPwmServlet.handleRequest(AbstractPwmServlet.java:110)
	at password.pwm.http.servlet.AbstractPwmServlet.doPost(AbstractPwmServlet.java:69)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:648)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:230)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at password.pwm.http.filter.AbstractPwmFilter$PwmFilterChain.doFilter(AbstractPwmFilter.java:138)
	at password.pwm.http.filter.SessionFilter.processFilter(SessionFilter.java:99)
	at password.pwm.http.filter.AbstractPwmFilter.doFilter(AbstractPwmFilter.java:89)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at password.pwm.http.filter.AbstractPwmFilter$PwmFilterChain.doFilter(AbstractPwmFilter.java:138)
	at password.pwm.http.filter.ApplicationModeFilter.processFilter(ApplicationModeFilter.java:73)
	at password.pwm.http.filter.AbstractPwmFilter.doFilter(AbstractPwmFilter.java:89)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at password.pwm.http.filter.AbstractPwmFilter$PwmFilterChain.doFilter(AbstractPwmFilter.java:138)
	at password.pwm.http.filter.ObsoleteUrlFilter.processFilter(ObsoleteUrlFilter.java:50)
	at password.pwm.http.filter.AbstractPwmFilter.doFilter(AbstractPwmFilter.java:89)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at password.pwm.http.filter.RequestInitializationFilter.initializeServletRequest(RequestInitializationFilter.java:209)
	at password.pwm.http.filter.RequestInitializationFilter.doFilter(RequestInitializationFilter.java:128)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at password.pwm.http.filter.GZIPFilter.doFilter(GZIPFilter.java:73)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:474)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:624)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:349)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:783)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:798)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1434)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Unknown Source)
2017-03-15T11:30:30Z, FATAL, servlet.AbstractPwmServlet, 5051 ERROR_DB_UNAVAILABLE (unexpected error trying to store token in datastore: 5051 ERROR_DB_UNAVAILABLE (put operation failed: String or binary data would be truncated.))
2017-03-15T11:30:30Z, ERROR, http.PwmResponse, {151} 5051 ERROR_DB_UNAVAILABLE (unexpected error trying to store token in datastore: 5051 ERROR_DB_UNAVAILABLE (put operation failed: String or binary data would be truncated.)) [192.168.1.231]
2017-03-15T11:31:38Z, FATAL, servlet.AbstractPwmServlet, 5051 ERROR_DB_UNAVAILABLE (unexpected error trying to store token in datastore: 5051 ERROR_DB_UNAVAILABLE (put operation failed: String or binary data would be truncated.))
2017-03-15T11:31:38Z, ERROR, http.PwmResponse, {151} 5051 ERROR_DB_UNAVAILABLE (unexpected error trying to store token in datastore: 5051 ERROR_DB_UNAVAILABLE (put operation failed: String or binary data would be truncated.)) [192.168.1.231]
2017-03-15T11:31:39Z, ERROR, state.CryptoCookieBeanImpl, {151} error reading existing LoginServletBean cookie bean: 5076 ERROR_CRYPT_ERROR (unexpected error performing simple decrypt operation: 5076 ERROR_CRYPT_ERROR (unexpected error performing simple decrypt operation: Tag mismatch!)) [192.168.1.231]
2017-03-15T11:31:43Z, FATAL, servlet.AbstractPwmServlet, 5051 ERROR_DB_UNAVAILABLE (unexpected error trying to store token in datastore: 5051 ERROR_DB_UNAVAILABLE (put operation failed: String or binary data would be truncated.))
2017-03-15T11:31:43Z, ERROR, http.PwmResponse, {151} 5051 ERROR_DB_UNAVAILABLE (unexpected error trying to store token in datastore: 5051 ERROR_DB_UNAVAILABLE (put operation failed: String or binary data would be truncated.)) [192.168.1.231]
2017-03-15T11:31:45Z, ERROR, state.CryptoCookieBeanImpl, {151} error reading existing LoginServletBean cookie bean: 5076 ERROR_CRYPT_ERROR (unexpected error performing simple decrypt operation: 5076 ERROR_CRYPT_ERROR (unexpected error performing simple decrypt operation: Tag mismatch!)) [192.168.1.231]
2017-03-15T11:31:50Z, FATAL, servlet.AbstractPwmServlet, 5051 ERROR_DB_UNAVAILABLE (unexpected error trying to store token in datastore: 5051 ERROR_DB_UNAVAILABLE (put operation failed: String or binary data would be truncated.))
2017-03-15T11:31:50Z, ERROR, http.PwmResponse, {151} 5051 ERROR_DB_UNAVAILABLE (unexpected error trying to store token in datastore: 5051 ERROR_DB_UNAVAILABLE (put operation failed: String or binary data would be truncated.)) [192.168.1.231]
2017-03-15T11:31:59Z, FATAL, servlet.AbstractPwmServlet, 5051 ERROR_DB_UNAVAILABLE (unexpected error trying to store token in datastore: 5051 ERROR_DB_UNAVAILABLE (put operation failed: String or binary data would be truncated.))
2017-03-15T11:31:59Z, ERROR, http.PwmResponse, {151} 5051 ERROR_DB_UNAVAILABLE (unexpected error trying to store token in datastore: 5051 ERROR_DB_UNAVAILABLE (put operation failed: String or binary data would be truncated.)) [192.168.1.231]
2017-03-15T11:32:09Z, ERROR, state.CryptoCookieBeanImpl, {151} error reading existing LoginServletBean cookie bean: 5076 ERROR_CRYPT_ERROR (unexpected error performing simple decrypt operation: 5076 ERROR_CRYPT_ERROR (unexpected error performing simple decrypt operation: Tag mismatch!)) [192.168.1.231]
2017-03-15T11:32:13Z, FATAL, servlet.AbstractPwmServlet, 5051 ERROR_DB_UNAVAILABLE (unexpected error trying to store token in datastore: 5051 ERROR_DB_UNAVAILABLE (put operation failed: String or binary data would be truncated.))
2017-03-15T11:32:13Z, ERROR, http.PwmResponse, {151} 5051 ERROR_DB_UNAVAILABLE (unexpected error trying to store token in datastore: 5051 ERROR_DB_UNAVAILABLE (put operation failed: String or binary data would be truncated.)) [192.168.1.231]
2017-03-15T11:33:59Z, ERROR, state.CryptoCookieBeanImpl, {151} error reading existing LoginServletBean cookie bean: 5076 ERROR_CRYPT_ERROR (unexpected error performing simple decrypt operation: 5076 ERROR_CRYPT_ERROR (unexpected error performing simple decrypt operation: Tag mismatch!)) [192.168.1.231]
2017-03-15T11:34:06Z, INFO , auth.LDAPAuthenticationRequest, {151} authID=7, successful ldap authentication for UserIdentity{"userDN":"CN=some user,OU=Users,OU=XXX-GOT,OU=XXX,DC=XXX-XXX,DC=net","ldapProfile":"default"} (32ms) type: AUTHENTICATED, using strategy BIND, using proxy connection: false, returning bind dn: CN=some user,OU=Users,OU=XXX-GOT,OU=XXX,DC=XXX-XXX,DC=net [192.168.1.231]
2017-03-15T11:34:06Z, INFO , event.AuditService, audit event: {"perpetratorID":"someuserid","perpetratorDN":"CN=some user,OU=Users,OU=XXX-GOT,OU=XXX,DC=XXX-XXX,DC=net","perpetratorLdapProfile":"default","sourceAddress":"192.168.1.231","sourceHost":"192.168.1.231","type":"USER","eventCode":"AUTHENTICATE","guid":"43242422-2342-2424-a3bd-62031b53d507","timestamp":"2017-03-15T11:34:06.271Z","message":"type=AUTHENTICATED, source=LOGIN_FORM","narrative":"someuserid (CN=some user,OU=Users,OU=XXX-GOT,OU=XXX,DC=XXX-XXX,DC=net) has authenticated","xdasTaxonomy":"XDAS_AE_AUTHENTICATE_ACCOUNT","xdasOutcome":"XDAS_OUT_SUCCESS"}
2017-03-15T11:34:13Z, ERROR, state.CryptoCookieBeanImpl, {152} error reading existing LoginServletBean cookie bean: 5076 ERROR_CRYPT_ERROR (unexpected error performing simple decrypt operation: 5076 ERROR_CRYPT_ERROR (unexpected error performing simple decrypt operation: Tag mismatch!)) [192.168.1.231]

```

I have database access are reporting OK and I have selected database as template. 

Token are also set do use the database.

**Comment by subst4nc3** [comment]
same behavior here...

**Comment by romoka** [comment]
Assuming you are using a remote Database as your storage option: this is what I did.
I am using MySQL as my remote storage: Increasing the length of column **id** in table **tokens** solved this error.
In my case, I ran the following MySQL alter table query:

`ALTER TABLE `tokens` CHANGE `id` `id` VARCHAR(255) NOT NULL;`
