### ISSUE TITLE
NullPointerException attempting to use Admin Page

### ISSUE THREAD

**Issue by danieljimenez** [pwm-project/pwm#185]
`5015 ERROR_UNKNOWN (unexpected error processing request: An exception occurred processing JSP page [/WEB-INF/jsp/admin-dashboard.jsp] at line [427] [xxxxxxx]
424:                                 Local Audit Records
425:                             </td>
426:                             <td>
427:                                 <%= dashboard_pwmApplication.getAuditManager().sizeToDebugString() %>
428:                             </td>
429:                         </tr>
430:                         <tr>
Stacktrace:
org.apache.jasper.JasperException: An exception occurred processing JSP page [/WEB-INF/jsp/admin-dashboard.jsp] at line [427]
424:                                 Local Audit Records
425:                             </td>
426:                             <td>
427:                                 <%= dashboard_pwmApplication.getAuditManager().sizeToDebugString() %>
428:                             </td>
429:                         </tr>
430:                         <tr>
Stacktrace:
	at org.apache.jasper.servlet.JspServletWrapper.handleJspException(JspServletWrapper.java:584)
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:481)
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:385)
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:329)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:728)
	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:467)
	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:392)
	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:311)
	at password.pwm.http.PwmResponse.forwardToJsp(PwmResponse.java:84)
	at password.pwm.http.PwmRequest.forwardToJsp(PwmRequest.java:140)
	at password.pwm.http.servlet.AdminServlet.forwardToJsp(AdminServlet.java:257)
	at password.pwm.http.servlet.AdminServlet.processAction(AdminServlet.java:141)
	at password.pwm.http.servlet.AbstractPwmServlet.handleRequest(AbstractPwmServlet.java:106)
	at password.pwm.http.servlet.AbstractPwmServlet.doGet(AbstractPwmServlet.java:55)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:635)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at password.pwm.http.filter.AbstractPwmFilter$PwmFilterChain.doFilter(AbstractPwmFilter.java:138)
	at password.pwm.http.filter.AuthorizationFilter.processFilter(AuthorizationFilter.java:84)
	at password.pwm.http.filter.AbstractPwmFilter.doFilter(AbstractPwmFilter.java:89)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at password.pwm.http.filter.AbstractPwmFilter$PwmFilterChain.doFilter(AbstractPwmFilter.java:138)
	at password.pwm.http.filter.AuthenticationFilter.processAuthenticatedSession(AuthenticationFilter.java:170)
	at password.pwm.http.filter.AuthenticationFilter.processFilter(AuthenticationFilter.java:109)
	at password.pwm.http.filter.AbstractPwmFilter.doFilter(AbstractPwmFilter.java:89)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at password.pwm.http.filter.AbstractPwmFilter$PwmFilterChain.doFilter(AbstractPwmFilter.java:138)
	at password.pwm.http.filter.CaptchaFilter.processFilter(CaptchaFilter.java:60)
	at password.pwm.http.filter.AbstractPwmFilter.doFilter(AbstractPwmFilter.java:89)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at password.pwm.http.filter.AbstractPwmFilter$PwmFilterChain.doFilter(AbstractPwmFilter.java:138)
	at password.pwm.http.filter.SessionFilter.processFilter(SessionFilter.java:84)
	at password.pwm.http.filter.AbstractPwmFilter.doFilter(AbstractPwmFilter.java:89)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at password.pwm.http.filter.AbstractPwmFilter$PwmFilterChain.doFilter(AbstractPwmFilter.java:138)
	at password.pwm.http.filter.ApplicationModeFilter.processFilter(ApplicationModeFilter.java:72)
	at password.pwm.http.filter.AbstractPwmFilter.doFilter(AbstractPwmFilter.java:89)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at password.pwm.http.filter.RequestInitializationFilter.initializeServletRequest(RequestInitializationFilter.java:190)
	at password.pwm.http.filter.RequestInitializationFilter.doFilter(RequestInitializationFilter.java:109)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at password.pwm.http.filter.GZIPFilter.doFilter(GZIPFilter.java:67)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:624)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:799)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:861)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1455)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
	at password.pwm.svc.event.AuditService.sizeToDebugString(AuditService.java:272)
	at org.apache.jsp.WEB_002dINF.jsp.admin_002ddashboard_jsp._jspService(admin_002ddashboard_jsp.java:1229)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:443)
	... 75 more
)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)`

**Comment by danieljimenez** [comment]
Let me know if I can provide any other info.

**Comment by MikePulcini** [comment]
I had this same issue and it appears to be resolved by https://github.com/pwm-project/pwm/commit/3511ad47614e0738e830116f9d66844640aadb2c. The corresponding build is [here](https://www.pwm-project.org/artifacts/pwm/pwm-1.8.0-SNAPSHOT-2017-07-18T05:58:15Z-pwm-bundle.zip).

**Comment by danieljimenez** [comment]
I'm running 1.8.0 and still seeing this. Just pulled this morning.
