### ISSUE TITLE
Fatal when logging in to /config

### ISSUE THREAD

**Issue by eici** [pwm-project/pwm#197]
2017-07-12T13:31:10Z, FATAL, servlet.AbstractPwmServlet, 5015 ERROR_UNKNOWN (unexpected error processing request: An exception occurred processing JSP page /WEB-INF/jsp/admin-dashboard.jsp at line 355

352:                             <% final List<HealthRecord> healthRecords = loopService.healthCheck(); %>
353:                         </td>
354:                         <td>
355:                             <% if (loopService.serviceInfo() != null && loopService.serviceInfo().getUsedStorageMethods() != null) { %>
356:                             <% for (final DataStorageMethod loopMethod : loopService.serviceInfo().getUsedStorageMethods()) { %>
357:                             <%=loopMethod.toString()%>
358:                             <br/>

Stacktrace:
org.apache.jasper.JasperException: An exception occurred processing JSP page /WEB-INF/jsp/admin-dashboard.jsp at line 355

352:                             <% final List<HealthRecord> healthRecords = loopService.healthCheck(); %>
353:                         </td>
354:                         <td>
355:                             <% if (loopService.serviceInfo() != null && loopService.serviceInfo().getUsedStorageMethods() != null) { %>
356:                             <% for (final DataStorageMethod loopMethod : loopService.serviceInfo().getUsedStorageMethods()) { %>
357:                             <%=loopMethod.toString()%>
358:                             <br/>

Stacktrace:
        at org.apache.jasper.servlet.JspServletWrapper.handleJspException(JspServletWrapper.java:575)
        at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:477)
        at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:395)
        at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:339)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:747)
        at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:485)
        at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:410)
        at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:337)
        at password.pwm.http.PwmResponse.forwardToJsp(PwmResponse.java:107)
        at password.pwm.http.PwmRequest.forwardToJsp(PwmRequest.java:155)
        at password.pwm.http.servlet.admin.AdminServlet.forwardToJsp(AdminServlet.java:391)
        at password.pwm.http.servlet.admin.AdminServlet.nextStep(AdminServlet.java:118)
        at password.pwm.http.servlet.ControlledPwmServlet.processAction(ControlledPwmServlet.java:158)
        at password.pwm.http.servlet.AbstractPwmServlet.handleRequest(AbstractPwmServlet.java:111)
        at password.pwm.http.servlet.AbstractPwmServlet.doGet(AbstractPwmServlet.java:62)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:624)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at password.pwm.http.filter.AbstractPwmFilter$PwmFilterChain.doFilter(AbstractPwmFilter.java:138)
        at password.pwm.http.filter.AuthorizationFilter.processFilter(AuthorizationFilter.java:84)
        at password.pwm.http.filter.AbstractPwmFilter.doFilter(AbstractPwmFilter.java:89)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at password.pwm.http.filter.AbstractPwmFilter$PwmFilterChain.doFilter(AbstractPwmFilter.java:138)
        at password.pwm.http.filter.AuthenticationFilter.processAuthenticatedSession(AuthenticationFilter.java:183)
        at password.pwm.http.filter.AuthenticationFilter.processFilter(AuthenticationFilter.java:118)
        at password.pwm.http.filter.AbstractPwmFilter.doFilter(AbstractPwmFilter.java:89)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at password.pwm.http.filter.AbstractPwmFilter$PwmFilterChain.doFilter(AbstractPwmFilter.java:138)
        at password.pwm.http.filter.SessionFilter.processFilter(SessionFilter.java:108)
        at password.pwm.http.filter.AbstractPwmFilter.doFilter(AbstractPwmFilter.java:89)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at password.pwm.http.filter.AbstractPwmFilter$PwmFilterChain.doFilter(AbstractPwmFilter.java:138)
        at password.pwm.http.filter.ApplicationModeFilter.processFilter(ApplicationModeFilter.java:74)
        at password.pwm.http.filter.AbstractPwmFilter.doFilter(AbstractPwmFilter.java:89)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at password.pwm.http.filter.AbstractPwmFilter$PwmFilterChain.doFilter(AbstractPwmFilter.java:138)
        at password.pwm.http.filter.ObsoleteUrlFilter.processFilter(ObsoleteUrlFilter.java:50)
        at password.pwm.http.filter.AbstractPwmFilter.doFilter(AbstractPwmFilter.java:89)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at password.pwm.http.filter.RequestInitializationFilter.initializeServletRequest(RequestInitializationFilter.java:210)
        at password.pwm.http.filter.RequestInitializationFilter.doFilter(RequestInitializationFilter.java:129)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at password.pwm.http.filter.GZIPFilter.doFilter(GZIPFilter.java:73)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
        at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:956)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:436)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1078)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)
        at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:318)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
        at password.pwm.svc.telemetry.TelemetryService.serviceInfo(TelemetryService.java:233)
        at org.apache.jsp.WEB_002dINF.jsp.admin_002ddashboard_jsp._jspService(admin_002ddashboard_jsp.java:1025)
        at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
        at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:439)
        ... 74 more
)

with the latest Build: pwm-1.8.0-SNAPSHOT-2017-07-12T04:25:11Z

**Comment by MikePulcini** [comment]
I had this same issue and it appears to be resolved by https://github.com/pwm-project/pwm/commit/3511ad47614e0738e830116f9d66844640aadb2c. The corresponding build is [here](https://www.pwm-project.org/artifacts/pwm/pwm-1.8.0-SNAPSHOT-2017-07-18T05:58:15Z-pwm-bundle.zip).

**Comment by eici** [comment]
@MikePulcini Thanks! Using the latest Build resolved the Issue!
