### ISSUE TITLE
Nullpointer when trying to recuperate password with "forgot password"

### ISSUE THREAD

**Issue by lucasdiedrich** [pwm-project/pwm#212]
Hello guys, for some reason i'm getting the error below when trying to recuperate my password, i choosed the method where he sends one new password to the user email.

![image](https://user-images.githubusercontent.com/817482/29383128-83e39f2e-82a5-11e7-9f06-180ab2642f36.png)
logs:
```bash
2017-08-16T20:07:04Z, INFO , forgottenpw.ForgottenPasswordServlet, {127} user successfully supplied password recovery responses, emailing new password to: uid=lucas.diedrich,cn=users,cn=accounts,dc=unila [10.80.14.12]
2017-08-16T20:07:04Z, DEBUG, http.PwmSession, {127} unauthenticate session from 10.80.14.12 [10.80.14.12]
2017-08-16T20:07:04Z, FATAL, servlet.AbstractPwmServlet, {127} unexpected error: 5015 ERROR_UNKNOWN (unexpected error processing request: null [10.80.14.12]
java.lang.NullPointerException
	at password.pwm.http.SessionManager.checkPermission(SessionManager.java:196)
	at password.pwm.util.operations.PasswordUtility.setActorPassword(PasswordUtility.java:278)
	at password.pwm.http.servlet.forgottenpw.ForgottenPasswordServlet.processSendNewPassword(ForgottenPasswordServlet.java:1058)
	at password.pwm.http.servlet.forgottenpw.ForgottenPasswordServlet.nextStep(ForgottenPasswordServlet.java:897)
	at password.pwm.http.servlet.ControlledPwmServlet.processAction(ControlledPwmServlet.java:158)
	at password.pwm.http.servlet.AbstractPwmServlet.handleRequest(AbstractPwmServlet.java:111)
	at password.pwm.http.servlet.AbstractPwmServlet.doGet(AbstractPwmServlet.java:62)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:635)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at password.pwm.http.filter.AbstractPwmFilter$PwmFilterChain.doFilter(AbstractPwmFilter.java:138)
	at password.pwm.http.filter.SessionFilter.processFilter(SessionFilter.java:108)
	at password.pwm.http.filter.AbstractPwmFilter.doFilter(AbstractPwmFilter.java:89)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at password.pwm.http.filter.AbstractPwmFilter$PwmFilterChain.doFilter(AbstractPwmFilter.java:138)
	at password.pwm.http.filter.ApplicationModeFilter.processFilter(ApplicationModeFilter.java:74)
	at password.pwm.http.filter.AbstractPwmFilter.doFilter(AbstractPwmFilter.java:89)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at password.pwm.http.filter.AbstractPwmFilter$PwmFilterChain.doFilter(AbstractPwmFilter.java:138)
	at password.pwm.http.filter.ObsoleteUrlFilter.processFilter(ObsoleteUrlFilter.java:50)
	at password.pwm.http.filter.AbstractPwmFilter.doFilter(AbstractPwmFilter.java:89)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at password.pwm.http.filter.RequestInitializationFilter.initializeServletRequest(RequestInitializationFilter.java:210)
	at password.pwm.http.filter.RequestInitializationFilter.doFilter(RequestInitializationFilter.java:129)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at password.pwm.http.filter.GZIPFilter.doFilter(GZIPFilter.java:73)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:799)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1457)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
)
2017-08-16T20:07:04Z, ERROR, http.PwmResponse, {127} 5015 ERROR_UNKNOWN (unexpected error processing request: null [10.80.14.12]
java.lang.NullPointerException
	at password.pwm.http.SessionManager.checkPermission(SessionManager.java:196)
	at password.pwm.util.operations.PasswordUtility.setActorPassword(PasswordUtility.java:278)
	at password.pwm.http.servlet.forgottenpw.ForgottenPasswordServlet.processSendNewPassword(ForgottenPasswordServlet.java:1058)
	at password.pwm.http.servlet.forgottenpw.ForgottenPasswordServlet.nextStep(ForgottenPasswordServlet.java:897)
	at password.pwm.http.servlet.ControlledPwmServlet.processAction(ControlledPwmServlet.java:158)
	at password.pwm.http.servlet.AbstractPwmServlet.handleRequest(AbstractPwmServlet.java:111)
	at password.pwm.http.servlet.AbstractPwmServlet.doGet(AbstractPwmServlet.java:62)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:635)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at password.pwm.http.filter.AbstractPwmFilter$PwmFilterChain.doFilter(AbstractPwmFilter.java:138)
	at password.pwm.http.filter.SessionFilter.processFilter(SessionFilter.java:108)
	at password.pwm.http.filter.AbstractPwmFilter.doFilter(AbstractPwmFilter.java:89)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at password.pwm.http.filter.AbstractPwmFilter$PwmFilterChain.doFilter(AbstractPwmFilter.java:138)
	at password.pwm.http.filter.ApplicationModeFilter.processFilter(ApplicationModeFilter.java:74)
	at password.pwm.http.filter.AbstractPwmFilter.doFilter(AbstractPwmFilter.java:89)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at password.pwm.http.filter.AbstractPwmFilter$PwmFilterChain.doFilter(AbstractPwmFilter.java:138)
	at password.pwm.http.filter.ObsoleteUrlFilter.processFilter(ObsoleteUrlFilter.java:50)
	at password.pwm.http.filter.AbstractPwmFilter.doFilter(AbstractPwmFilter.java:89)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at password.pwm.http.filter.RequestInitializationFilter.initializeServletRequest(RequestInitializationFilter.java:210)
	at password.pwm.http.filter.RequestInitializationFilter.doFilter(RequestInitializationFilter.java:129)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at password.pwm.http.filter.GZIPFilter.doFilter(GZIPFilter.java:73)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:799)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1457)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
)
2017-08-16T20:07:04Z, DEBUG, http.PwmResponse, {127} forcing logout due to error 5015 ERROR_UNKNOWN (unexpected error processing request: null [10.80.14.12]
java.lang.NullPointerException
	at password.pwm.http.SessionManager.checkPermission(SessionManager.java:196)
	at password.pwm.util.operations.PasswordUtility.setActorPassword(PasswordUtility.java:278)
	at password.pwm.http.servlet.forgottenpw.ForgottenPasswordServlet.processSendNewPassword(ForgottenPasswordServlet.java:1058)
	at password.pwm.http.servlet.forgottenpw.ForgottenPasswordServlet.nextStep(ForgottenPasswordServlet.java:897)
	at password.pwm.http.servlet.ControlledPwmServlet.processAction(ControlledPwmServlet.java:158)
	at password.pwm.http.servlet.AbstractPwmServlet.handleRequest(AbstractPwmServlet.java:111)
	at password.pwm.http.servlet.AbstractPwmServlet.doGet(AbstractPwmServlet.java:62)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:635)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at password.pwm.http.filter.AbstractPwmFilter$PwmFilterChain.doFilter(AbstractPwmFilter.java:138)
	at password.pwm.http.filter.SessionFilter.processFilter(SessionFilter.java:108)
	at password.pwm.http.filter.AbstractPwmFilter.doFilter(AbstractPwmFilter.java:89)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at password.pwm.http.filter.AbstractPwmFilter$PwmFilterChain.doFilter(AbstractPwmFilter.java:138)
	at password.pwm.http.filter.ApplicationModeFilter.processFilter(ApplicationModeFilter.java:74)
	at password.pwm.http.filter.AbstractPwmFilter.doFilter(AbstractPwmFilter.java:89)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at password.pwm.http.filter.AbstractPwmFilter$PwmFilterChain.doFilter(AbstractPwmFilter.java:138)
	at password.pwm.http.filter.ObsoleteUrlFilter.processFilter(ObsoleteUrlFilter.java:50)
	at password.pwm.http.filter.AbstractPwmFilter.doFilter(AbstractPwmFilter.java:89)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at password.pwm.http.filter.RequestInitializationFilter.initializeServletRequest(RequestInitializationFilter.java:210)
	at password.pwm.http.filter.RequestInitializationFilter.doFilter(RequestInitializationFilter.java:129)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at password.pwm.http.filter.GZIPFilter.doFilter(GZIPFilter.java:73)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:799)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1457)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
```

Any ideas?

**Comment by neb382** [comment]
hi lucas, did you find any solution for this problem? i´m running into the same

**Comment by lucasdiedrich** [comment]
Unfortunately i didn't, i gave up from upgrading my PWM.

**Comment by neb382** [comment]
thx for your response. So you are using an earlier version which is okay?

**Comment by lucasdiedrich** [comment]
Actually i'm using an 2015 version which has lots of other bugs, but at least the user can recover his password.

**Comment by neb382** [comment]
i guess you also sending out the password  via email. I noticed when allowing  the user to type in a new password than this null pointer exception is not thrown. So it must be related to "processSendNewPassword" by email
