### ISSUE TITLE
Unable to Connect to Database

### ISSUE THREAD

**Issue by eici** [pwm-project/pwm#230]
I get the following error:

Database | WARN | unable to initialize database: exception initializing database service: 5051 ERROR_DB_UNAVAILABLE (error connecting to database: java.sql.SQLNonTransientConnectionException: Could not connect to address=(host=xx-yy-zz.aa.bb)(port=3306)(type=master) : Permission denied (connect failed), cause:java.net.SocketException: Permission denied (connect failed))

Stacktrace:
password.pwm.error.PwmUnrecoverableException: 5051 ERROR_DB_UNAVAILABLE (unable to initialize database: exception initializing database service: 5051 ERROR_DB_UNAVAILABLE (error connecting to database: java.sql.SQLNonTransientConnectionException: Could not connect to address=(host=em-srv-data.emundo.local)(port=3306)(type=master) : Permission denied (connect failed), cause:java.net.SocketException: Permission denied (connect failed)))
	at password.pwm.util.db.DatabaseService.getAccessor(DatabaseService.java:285)
	at password.pwm.util.db.DatabaseDataStore.size(DatabaseDataStore.java:82)
	at password.pwm.svc.token.DataStoreTokenMachine.size(DataStoreTokenMachine.java:138)
	at password.pwm.svc.token.DataStoreTokenMachine.cleanup(DataStoreTokenMachine.java:46)
	at password.pwm.svc.token.TokenService$CleanerTask.run(TokenService.java:387)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

with:
mariadb-java-client-2.1.2.jar
pwm-1.8.0-SNAPSHOT-2017-07-18T05:58:15Z-pwm-bundle.zip

**Fun thing is**: i can connect perfectly normal with any other sql-client (or telnet) from the same machine!
Anybody got any idea what can cause that?

**Comment by eici** [comment]
Found the Problem... CentOS 7.3 to CentOS 7.4 update changed the selinux policies... Tomcat can't access sockets with the default... "cat /var/log/audit* | audit2allow" helped!
