### ISSUE TITLE
Administration Module Issue

### ISSUE THREAD

**Issue by isaachall77** [pwm-project/pwm#508]
The issue I am seeing is that if the Public Module "Activate Account" is enabled _at all_, it immediately breaks the Administration Module. And by breaks, I mean when you login as an administrator-level account, and click "Administration", it returns an error code and logs the account out.

1. Modules -> Public -> User Activation -> Settings
2. Enable the Module
3. Save and reload the server
4. Login with an admin account
5. Click Administration

I have tested this with two server instances and replicated it both times.

**Comment by jrivard** [comment]
What version of PWM?  Whats the error?

**Comment by isaachall77** [comment]
PWM version 2.0.0

The error is PWM 5015: An error has occurred. If this error occurs repeatedly please contact your help desk.

And these are the log messages:

`2019-10-02T15:14:07Z, FATAL, servlet.AbstractPwmServlet, {3vZN5,pwma} unexpected error: 5015 ERROR_INTERNAL (unexpected error processing request: java.lang.IllegalArgumentException: reading of setting activateUser.token.sendMethod requires a non-null profileID [1D8BA6B1B8F239E4C49ED771A84976ED8F6BFC47]) [10.2.2.102]
2019-10-02T15:14:07Z, ERROR, http.PwmResponse, {3vZN5,pwma} 5015 ERROR_INTERNAL (unexpected error processing request: java.lang.IllegalArgumentException: reading of setting activateUser.token.sendMethod requires a non-null profileID [1D8BA6B1B8F239E4C49ED771A84976ED8F6BFC47]) [10.2.2.102]
2019-10-02T15:14:25Z, ERROR, node.NodeMachine, 5093 ERROR_NODE_SERVICE_ERROR (error writing node service heartbeat: 5079 ERROR_LDAP_DATA_ERROR (error writing node service data user 'CN=PWM Test User,OU=Admin,DC=aims,DC=edu (staff)' attribute 'pwmData', error: javax.naming.directory.NoSuchAttributeException: [LDAP: error code 16 - 00000057: LdapErr: DSID-0C090F64, comment: Error in attribute conversion operation, data 0, v3839]))
`

As well as a series of these:

`java.lang.IllegalArgumentException: reading of setting activateUser.token.sendMethod requires a non-null profileID
        at password.pwm.config.stored.StoredConfigurationImpl.readSetting(StoredConfigurationImpl.java:786)
        at password.pwm.config.stored.StoredConfigurationImpl.readSetting(StoredConfigurationImpl.java:779)
        at password.pwm.config.Configuration.readStoredValue(Configuration.java:1015)
        at password.pwm.config.Configuration.readSettingAsEnum(Configuration.java:188)
        at password.pwm.svc.token.TokenService.tokensAreUsedInConfig(TokenService.java:485)
        at password.pwm.svc.token.TokenService.healthCheck(TokenService.java:334)
        at password.pwm.health.HealthMonitor.doHealthChecks(HealthMonitor.java:242)
        at password.pwm.health.HealthMonitor.access$500(HealthMonitor.java:56)
        at password.pwm.health.HealthMonitor$ImmediateJob.run(HealthMonitor.java:291)
        at password.pwm.health.HealthMonitor$UpdateJob.run(HealthMonitor.java:278)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)`

**Comment by jrivard** [comment]
fixed in b7ff8e10423c39eb9c4786cb19221d6cdf64f3bb.  

Note: this bug requires new user registration module to be disabled to be seen.
