### ISSUE TITLE
Unable to validate password on newuser form

### ISSUE THREAD

**Issue by idwright** [pwm-project/pwm#52]
I get the following exception thrown when attempting to create a new user - it is connected to checking the password.
Using latest code from github as of today with minimal configuration

2016-02-17T15:48:10Z, FATAL, servlet.AbstractPwmServlet, 5015 ERROR_UNKNOWN (unexpected error processing request: null
java.lang.NullPointerException
	at password.pwm.PwmApplication.getProxiedChaiUser(PwmApplication.java:324)
	at password.pwm.ldap.LdapUserDataReader.appProxiedReader(LdapUserDataReader.java:65)
	at password.pwm.util.macro.MacroMachine.forUser(MacroMachine.java:246)
	at password.pwm.util.PwmPasswordRuleValidator.internalPwmPolicyValidator(PwmPasswordRuleValidator.java:222)
	at password.pwm.util.PwmPasswordRuleValidator.internalPwmPolicyValidator(PwmPasswordRuleValidator.java:157)
	at password.pwm.util.PwmPasswordRuleValidator.validate(PwmPasswordRuleValidator.java:139)
	at password.pwm.util.PwmPasswordRuleValidator.testPassword(PwmPasswordRuleValidator.java:92)

**Comment by jrivard** [comment]
This is similar to issue 50 and should have been fixed in the current trunk builds.  Please re-open if it is still occurring.
